blank_issues_enabled: false
contact_links:
  - name: "ðŸ’¬ Discussion"
    url: "https://github.com/wp-spaghetti/bedrock-autoloader-mu/discussions"
    about: "For questions, ideas, and general discussion"
    
  - name: "ðŸ“– Documentation"
    url: "https://github.com/wp-spaghetti/bedrock-autoloader-mu"
    about: "Read the documentation before asking questions"
    
  - name: "ðŸ’Œ Security Issues"
    url: "https://github.com/wp-spaghetti/bedrock-autoloader-mu/security"
    about: "For security vulnerabilities (private reporting)"